import requests
import os
from dotenv import load_dotenv
from typing import Optional, List, Dict, Any
from utils.logger import get_logger
import datetime

logger = get_logger(__name__)

class NotionService:
    def __init__(self, token: Optional[str] = None):
        if not token:
            load_dotenv(".env.local")
            token = os.getenv("NOTION_TOKEN")
        self.token = token
        self.headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json", "Notion-Version": "2022-06-28"} if token else {}

    def create_page(self, database_id: str, title: str, properties: Optional[Dict[str, Any]] = None) -> Optional[Dict[str, Any]]:
        if not self.token: return {"id": "mock_page"}
        payload = {"parent": {"database_id": database_id}, "properties": {"Name": {"title": [{"text": {"content": title}}]}}}
        if properties: payload["properties"].update(properties)
        try:
            res = requests.post("https://api.notion.com/v1/pages", headers=self.headers, json=payload)
            res.raise_for_status()
            return res.json()
        except Exception as e:
            logger.error(f"Notion Create Error: {e}")
            return None

    def query_database(self, database_id: str, filter_criteria: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]:
        if not self.token: return []
        try:
            res = requests.post(f"https://api.notion.com/v1/databases/{database_id}/query", headers=self.headers, json={"filter": filter_criteria} if filter_criteria else {})
            res.raise_for_status()
            return res.json().get("results", [])
        except Exception as e:
            logger.error(f"Notion Query Error: {e}")
            return []

    def get_page_content(self, page_id: str) -> str:
        if not self.token: return ""
        url = f"https://api.notion.com/v1/blocks/{page_id}/children"
        resp = requests.get(url, headers=self.headers)
        if resp.status_code == 200:
            blocks = resp.json().get("results", [])
            text = []
            for b in blocks:
                if b["type"] == "paragraph":
                    text.extend([t["plain_text"] for t in b["paragraph"]["rich_text"]])
            return "\n".join(text)
        return ""

    def _get_target_database(self, name: str = "BlueLays Knowledge Base") -> Optional[str]:
        try:
            search_url = "https://api.notion.com/v1/search"
            payload = {
                "query": name,
                "filter": {"value": "database", "property": "object"},
                "page_size": 1
            }
            resp = requests.post(search_url, headers=self.headers, json=payload)
            resp.raise_for_status()
            results = resp.json().get("results", [])
            
            if results:
                return results[0]["id"]
            
            payload.pop("query") 
            resp = requests.post(search_url, headers=self.headers, json=payload)
            results = resp.json().get("results", [])
            
            if results:
                return results[0]["id"]
                
        except Exception as e:
            logger.error(f"Notion DB Search Error: {e}")
            
        return None

    def create_page(self, title: str, content_text: str) -> Optional[str]:
        if not self.token:
            logger.error("No Notion Token provided.")
            return None

        database_id = self._get_target_database()
        if not database_id:
            logger.error("No suitable Notion Database found to save the note.")
            return None
        
        url = "https://api.notion.com/v1/pages"
        
        blocks = []
        blocks.append({
            "object": "block",
            "type": "callout",
            "callout": {
                "rich_text": [{"type": "text", "text": {"content": f"Generated by BlueLays Agent on {datetime.date.today()}"}}],
                "icon": {"emoji": "🤖"}
            }
        })
        
        for line in content_text.split('\n'):
            line = line.strip()
            if not line: continue
            
            if line.startswith("- "):
                blocks.append({
                    "object": "block",
                    "type": "bulleted_list_item",
                    "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": line[2:]}}]}
                })
            elif line.startswith("### "):
                 blocks.append({
                    "object": "block",
                    "type": "heading_3",
                    "heading_3": {"rich_text": [{"type": "text", "text": {"content": line[4:]}}]}
                })
            elif line.startswith("## "):
                 blocks.append({
                    "object": "block",
                    "type": "heading_2",
                    "heading_2": {"rich_text": [{"type": "text", "text": {"content": line[3:]}}]}
                })
            else:
                blocks.append({
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {"rich_text": [{"type": "text", "text": {"content": line}}]}
                })

        data = {
            "parent": {"database_id": database_id},
            "properties": {
                "Name": { "title": [{"text": {"content": title}}] }
            },
            "children": blocks
        }
        
        try:
            resp = requests.post(url, headers=self.headers, json=data)
            resp.raise_for_status()
            return resp.json().get("url")
        except Exception as e:
             logger.error(f"Notion Create Error: {e}")
             try:
                 logger.error(f"Notion Reponse: {resp.text}")
             except: pass
             return None
